name: Build vLLM
run-name: Build vLLM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Publish artifacts produced by this job'
        required: false
        type: boolean
        default: false
      pushLatest:
        description: 'Tag artifacts produced by this job as latest-*'
        required: false
        type: boolean
        default: false
      releaseTag:
        description: 'Release tag'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: native_linux_cpu
            dockerfile: generic.Dockerfile
            context: .
            build_args: |
              BASE_IMAGE=ubuntu:24.04
            output_dir: out-cpu
          
#          - name: native_linux_cuda
#            dockerfile: cuda.Dockerfile
#            context: .
#            build_args: |
#              CUDA_VERSION=12.9.0
#              CUDA_IMAGE_VARIANT=ubuntu24.04
#            output_dir: out-cuda
    
    name: Build ${{ matrix.name }}
    
    steps:
    - name: Free Disk Space
      shell: bash
      run: |
        sudo docker rmi "$(docker image ls -aq)" >/dev/null 2>&1 || true
        sudo rm -rf \
          /usr/share/dotnet /usr/local/lib/android /opt/ghc \
          /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
          /usr/lib/jvm || true
        echo "=== Disk space after cleanup ==="
        df -h
    
    - name: Reconfigure Docker data-root
      run: |
        set -e
        sudo mkdir -p /mnt/docker /etc/docker
        echo '{"data-root": "/mnt/docker"}' > /tmp/daemon.json
        sudo mv /tmp/daemon.json /etc/docker/daemon.json
        sudo systemctl restart docker.service
        echo "=== Disk space after Docker reconfiguration ==="
        df -h
    
    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        submodules: 'true'

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
        password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: "lab:latest"
        driver: cloud
        endpoint: "docker/make-product-smarter"
        install: true

    - name: Build vLLM (${{ matrix.name }})
      uses: docker/build-push-action@v5
      with:
        file: ${{ github.workspace }}/${{ matrix.dockerfile }}
        #platforms: linux/amd64, linux/arm64
        platforms: linux/amd64
        context: ${{ github.workspace }}/${{ matrix.context }}
        build-args: ${{ matrix.build_args }}
        push: false
        sbom: true
        provenance: mode=max
        outputs: type=local,dest=${{ github.workspace }}/${{ matrix.output_dir }}
